### ISSUE TITLE
make readme file

### ISSUE THREAD

**Issue by DWAA1660** [naveenpoddar/discord-chatbot#1]
what is this even used for

**Comment by tvhsin** [comment]
it's kinds obvious if you just look at the code

**Comment by DWAA1660** [comment]
when you dont know js
is it bot or client side

**Comment by Aayush01411** [comment]
ODQ5MzQ5OTQwOTExMTQ0OTcw.YLZ4xg.QL4KszSIcQ5yzljXBbX7u7wKcg8

**Comment by ddodogames** [comment]
i mean it's just a index.js file, run it and boom you got a chatbot working, what's the point of having a readme file if you just looked at a one js file?

**Comment by naveenpoddar** [comment]
I've added the readme file for non coders
